name: rating
on:
  pull_request:
    paths:
      - ".github/workflows/rating.yml"
      - "app/**"
  workflow_dispatch:

concurrency:
  group: rating

jobs:
  rating:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY_PATH: ~/.ssh/id_rsa
    steps:
      - run: mkdir -p ~/.ssh
      - run: echo '${{ secrets.SSH_PRIVATE_KEY }}' > ${{ env.SSH_PRIVATE_KEY_PATH }} && chmod 400 ${{ env.SSH_PRIVATE_KEY_PATH }}
      - run: echo '${{ secrets.SSH_KNOWN_HOST_ED25519 }}' >> ~/.ssh/known_hosts
      - run: echo '${{ secrets.SSH_KNOWN_HOST_SHA2_NISTP256 }}' >> ~/.ssh/known_hosts
      - id: run_rating
        run: ssh -tt -i ${{ env.SSH_PRIVATE_KEY_PATH }} azureuser@env-rabbit.ftt2306.dabaas.net '~/rating.sh "${{ github.sha }}" "${{ github.ref }}"'
      - name: kill rating process
        if: steps.run_rating.outcome == 'cancelled'
        run: ssh -i ~/.ssh/id_rsa azureuser@env-rabbit.ftt2306.dabaas.net '~/kill_rating.sh'
