name: rating
on:
  pull_request:
    paths:
      - ".github/workflows/rating.yml"
      - "app/**"
  workflow_dispatch:

jobs:
  rating:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ~/.ssh
      - run: echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_rsa
      - id: run_rating
        run: ssh -t -i ~/.ssh/id_rsa azureuser@env-rabbit.ftt2306.dabaas.net '~/rating.sh "${{ github.sha }}" "${{ github.ref }}"'
      - name: kill rating process
        if: steps.run_rating.outcome == 'cancelled'
        run: ssh -i ~/.ssh/id_rsa azureuser@env-rabbit.ftt2306.dabaas.net '~/kill_rating.sh'
